name: witnet
description: A library to interface with the Witnet Protocol.
  - Ability to recover
  - build, sign, and send value transfers and data requests
  - communicate with a rust node or wallet server
  - communicate with the explorer

version: 0.1.5

homepage: https://github.com/witnet/witnet.dart
repository: https://github.com/witnet/witnet.dart

environment:
  sdk: '>=2.13.0 <3.0.0'

dev_dependencies:
  test: ^1.21.6

dependencies:
  cbor: ^5.1.1
  hex: ^0.2.0
  pointycastle: ^3.1.3
  path: ^1.4.1
  web_socket_channel: ^2.1.0
  async: ^2.6.1
  typed_data: ^1.3.0
  crypto: ^3.0.1
  http: ^0.13.3
  xml: ^6.1.0
  protobuf: ^2.1.0
