name: witnet
description: A library to interface with the Witnet Protocol.
  - Ability to recover
  - build, sign, and send value transfers and data requests
  - communicate with a rust node or wallet server
  - communicate with the explorer

version: 0.4.2

homepage: https://github.com/witnet/witnet.dart
repository: https://github.com/witnet/witnet.dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.9

dependencies:
  cbor: ^6.1.1
  hex: ^0.2.0
  pointycastle: ^3.1.3
  path: ^1.9.0
  web_socket_channel: ^2.4.1
  async: ^2.6.1
  typed_data: ^1.3.0
  crypto: ^3.0.1
  http: ^1.1.2
  xml: ^6.5.0
  protobuf: ^3.1.0
  fixnum: ^1.1.0

